name: map_env
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pip:
    - folium
    - pandas
    - streamlit
    - streamlit_folium
    - numpy
    - pyyaml
    - geopandas
  - python==3.9.12
